[package]
name = "§package§"
version = "§version§"
license = "MIT"
entrypoint = "lib/lib.typ"
authors = ["Lieven Vandevelde"]
description = "Doctoral and master's theses following guidelines at Ghent University and providing some additional functions and features."
repository = "https://github.com/lvandevelde/typst-minerva-thesis"
keywords = [
    "template",
    "thesis",
    "Ghent University",
    "UGent",
    "Universiteit Gent"
]
categories = [
    "model",
    "layout",
    "thesis",
]
compiler = "§typst-version§"

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
